namespace Repro2
{
[default_interface]
  unsealed runtimeclass RenderableView : Windows.UI.Xaml.FrameworkElement
  {
    RenderableView();
    Int32 Render();
  }

  [default_interface]
  unsealed runtimeclass GroupView : RenderableView
  {
    GroupView();
     Int32 RenderGroup();
  }

    [default_interface]
  runtimeclass SubSub : GroupView
  {
    SubSub();
     Int32 RenderBloop();
  }


}
